name: jatlantic's blog
title: jatlantic
url: https://jatlantic.github.io
baseurl: ""
show_excerpts: true
#twitter_username: sidinusofaiii
github_username: jatlantic
description: On machine learning, python, statistics and books
author: jatlantic
email: tbd
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
remote_theme: thelehhman/texture
#theme: texture

# Google Analytics
google_analytics: False

plugins:
  - "disqus-for-jekyll"
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - books.md
  - blog/index.html
  - index.html

sass:
  sass_dir: _sass

texture:
  title: jatlantic
  tagline: Data Scientist
  date_format: "%b %-d, %Y"
  style: red
  showNav: true
  social_links:
    #twitter: sidinusofaiii
    github:  jatlantic
    #linkedIn: in/username # format: locale/username
